### ISSUE TITLE
About Window Doesn't Close on "OK" Press

### ISSUE THREAD

**Issue by RotatingWires** [LDZPLN1/SDRTrunk-Monitor#1]
This isn't really too big of an issue of course, I just wanted to say thanks for making this. I recently left an issue on the SDRT github requesting a feature to auto-restart SDRT on a pipe error, then I found this! Really appreciate your work as this will save me from having to manually restart SDRT every time I get a pipe error. It's especially bad because I sometimes find out hours later when I'd have missed a ton of traffic. I haven't gotten a pipe error yet, but I'm assuming it works.

Update: it works!

For the actual issue though, it's just when I right click the tray icon, click about, then click "OK" and the window doesn't go away, that's all. I'd just click the X.

**Comment by LDZPLN1** [comment]
Thank you so much for the input… I’ll re-check that portion of the code.

 

Did you build from source or did you download the last MSI release?  Just curious because I generally don’t publish the most recent MSI files until I’m about 5 commits behind.

 

I had the same issues as you… pipe errors (some were ok, but after a bit things got wonky for me).

 

I am running 6 “cheap” SDRs monitoring 5 channels (Cary, NC, Raleigh, NC, 2 Johnston County, NC sites and one statewide VIPER site).. and the failures bugged the heck out of me (They tend to occur when I go to bed once my laptop goes into power saving mode). That’s why I wrote the code.

 

-Douglas

 

From: RotatingWires ***@***.***> 
Sent: Friday, June 9, 2023 19:25
To: LDZPLN1/SDRTrunk-Monitor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LDZPLN1/SDRTrunk-Monitor] About Window Doesn't Close on "OK" Press (Issue #1)

 

This isn't really too big of an issue of course, I just wanted to say thanks for making this. I recently left an issue on the SDRT github requesting a feature to auto-restart SDRT on a pipe error, then I found this! Really appreciate your work as this will save me from having to manually restart SDRT every time I get a pipe error. It's especially bad because I sometimes find out hours later when I'd have missed a ton of traffic. I haven't gotten a pipe error yet, but I'm assuming it works.

For the actual issue though, it's just when I right click the tray icon, click about, then click "OK" and the window doesn't go away, that's all. I'd just click the X.

**Comment by LDZPLN1** [comment]
Found the issue..., the about.vb file got deleted from the repo... currently rebuilding that file so it should be corrected in the next release. Secondary effects are that the Product name, version and copyright date are also missing.

**Comment by LDZPLN1** [comment]
Fixed in latest commit (release 1.2.2 includes this fix)

**Comment by RotatingWires** [comment]
> Did you build from source or did you download the last MSI release? Just curious because I generally don’t publish the most recent MSI files until I’m about 5 commits behind.
> […](#)

Yeah, I just downloaded the MSI file. Thanks for replying!
